-- MySQL Script generated by MySQL Workbench
-- Thu Nov 29 12:01:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema maximus
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `maximus` ;

-- -----------------------------------------------------
-- Schema maximus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maximus` DEFAULT CHARACTER SET utf8 ;
USE `maximus` ;

-- -----------------------------------------------------
-- Table `maximus`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maximus`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `maximus`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `nome` VARCHAR(60) NULL,
  `ra` VARCHAR(20) NULL,
  `ind_aluno` CHAR(1) NULL DEFAULT 'N' COMMENT 'Indicador de tipo de usuário',
  `ind_professor` CHAR(1) NULL DEFAULT 'N' COMMENT 'Indicador de tipo de usuário',
  `ind_secretaria` CHAR(1) NULL DEFAULT 'N' COMMENT 'Indicador de tipo de usuário',
  PRIMARY KEY (`id_usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maximus`.`materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maximus`.`materias` ;

CREATE TABLE IF NOT EXISTS `maximus`.`materias` (
  `id_materias` INT NOT NULL AUTO_INCREMENT,
  `materia` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(80) NULL,
  `usuarios_id_usuarios` INT NULL COMMENT 'Esse campo tem por objetivo receber o id do usuário do professor que leciona a matéria.',
  PRIMARY KEY (`id_materias`),
  INDEX `fk_Materias_Usuarios1_idx` (`usuarios_id_usuarios` ASC),
  CONSTRAINT `fk_Materias_Usuarios1`
    FOREIGN KEY (`usuarios_id_usuarios`)
    REFERENCES `maximus`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maximus`.`turnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maximus`.`turnos` ;

CREATE TABLE IF NOT EXISTS `maximus`.`turnos` (
  `id_turnos` INT NOT NULL AUTO_INCREMENT,
  `turno` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(60) NULL,
  PRIMARY KEY (`id_turnos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maximus`.`matriculas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maximus`.`matriculas` ;

CREATE TABLE IF NOT EXISTS `maximus`.`matriculas` (
  `id_matriculas` INT NOT NULL AUTO_INCREMENT,
  `presencas` INT NULL DEFAULT 0,
  `faltas` INT NULL DEFAULT 0,
  `nota` DECIMAL(3,1) NULL DEFAULT 0,
  `ind_ativo` CHAR(1) NULL DEFAULT 'N',
  `ind_revisao` CHAR(1) NULL DEFAULT 'N',
  `ind_revisado` CHAR(1) NULL DEFAULT 'N',
  `ind_aprovacao` CHAR(1) NULL DEFAULT 'N',
  `ind_reprovacao` CHAR(1) NULL DEFAULT 'N',
  `materias_id_materias` INT NOT NULL,
  `usuarios_id_usuarios` INT NOT NULL,
  `turnos_id_turnos` INT NOT NULL,
  PRIMARY KEY (`id_matriculas`),
  INDEX `fk_Matriculas_Materias1_idx` (`materias_id_materias` ASC),
  INDEX `fk_matriculas_usuarios1_idx` (`usuarios_id_usuarios` ASC),
  INDEX `fk_matriculas_turnos1_idx` (`turnos_id_turnos` ASC),
  CONSTRAINT `fk_Matriculas_Materias1`
    FOREIGN KEY (`materias_id_materias`)
    REFERENCES `maximus`.`materias` (`id_materias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matriculas_usuarios1`
    FOREIGN KEY (`usuarios_id_usuarios`)
    REFERENCES `maximus`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matriculas_turnos1`
    FOREIGN KEY (`turnos_id_turnos`)
    REFERENCES `maximus`.`turnos` (`id_turnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
